In [1]:
import json
import pandas as pd

In [2]:
def process_json(file_path):
    contexts_data = []
    questions_data = []

    with open(file_path, "r", encoding="utf-8") as file:
        json_data = json.load(file)
        for article in json_data["data"]:
            for paragraph in article["paragraphs"]:
                context = paragraph["context"]
                context_id = hash(context) 
                
                contexts_data.append({"context_id": context_id, "context": context})
                
                for qas in paragraph["qas"]:
                    if not qas["is_impossible"]:
                        questions_data.append({"context_id": context_id, "question": qas["question"]})
    
    return contexts_data, questions_data

In [3]:
contexts_train, questions_train = process_json("E:/Financial_Chatbot/PersianQA_Dataset/pqa_train.json")
contexts_train2, questions_train2 = process_json("E:/Financial_Chatbot/PersianQA_Dataset/train.json")

contexts_test, questions_test = process_json("E:/Financial_Chatbot/PersianQA_Dataset/pqa_test.json")
contexts_test2, questions_test2 = process_json("E:/Financial_Chatbot/PersianQA_Dataset/test.json")

contexts_combined = contexts_train + contexts_test + contexts_train2 + contexts_test2
questions_combined = questions_train + questions_test + questions_train2 + questions_test2

contexts_df = pd.DataFrame(contexts_combined)
questions_df = pd.DataFrame(questions_combined)

In [4]:
contexts_df

               context_id                                            context
0     7726203625027724684  شرکت فولاد مبارکۀ اصفهان، بزرگ‌ترین واحد صنعتی...
1     5864093557856031219  علوم رایانه یا علوم کامپیوتر به مجموعهٔ مطالعا...
2     3789459299051365926  رُبات ماشینی است که معمولاً قابل برنامه‌ریزی ت...
3    -8207967348368518793  درخت سیب (نام علمی: M. pumila) درختی برگریز از...
4     7674741263543023890  کتاب (وام‌واژه از زبان عربی، جمع: کُتُب) مجموع...
...                   ...                                                ...
4173  -208726758922459261  همهٔ آثار سعدی اعم از شعر و نثر در مجموعه‌ای ب...
4174  3906595627634675023  در سال ۱۳۲۱ مجموعهٔ سگ ولگرد را انتشار داده، ت...
4175 -2719889752324891761  او فرزند صدرالشعرا غلامحسین‌میرزا، نوهٔ ایرج پ...
4176 -8399387556451751741  بزرگ‌ترین لاک پشت موجود در طبیعت لاک پشت چرمی ...
4177 -8580872166056094092  در بخش شرقی توکیو رودهای سومیدا، آراکاوا، ادوگ...

[4178 rows x 2 columns]

In [5]:
questions_df

                context_id                                           question
0      7726203625027724684              شرکت فولاد مبارکه در کجا واقع شده است
1      7726203625027724684  فولاد مبارکه چند بار برنده جایزه شرکت دانشی را...
2      7726203625027724684     شرکت فولاد مبارکه در سال ۱۳۹۱ چه جایزه ای برد؟
3      7726203625027724684           بزرگ ترین مجموعه تولید فولاد ایران چیست؟
4      7726203625027724684                  فولاد مبارکه در چه سالی احداث شد؟
...                    ...                                                ...
26519 -8580872166056094092   میان رودهای تاما و آراکاوا کدام فلات قرار دارد ؟
26520 -8580872166056094092        رود تاما در کدام قسمت از توکیو جریان دارد ؟
26521 -8580872166056094092  کدام کوه در جزیره ایزو اوشیما در سال 1986 فورا...
26522 -8580872166056094092           رود تاما در توکیو چند کیلومتر طول دارد ؟
26523 -8580872166056094092  فلات موساشینو در توکیو میان کدام دو رود قرار د...

[26524 rows x 2 columns]

In [9]:
contexts_df.to_csv('df_contexts.csv', encoding='utf-8-sig', index=False, header=True)
questions_df.to_csv('df_questions.csv', encoding='utf-8-sig', index=False, header=True)